from .empresa import Empresa
from .usuario import Usuario
from .conductor import Conductor
from .dispositivogps import DispositivoGPS
from .vehiculo import Vehiculo
from .ubicacion import Ubicacion
from .tramo import Tramo
from .estadoViaje import EstadoViaje
from .ruta import Ruta
from .trip import Trip
from .posiciongps import PosicionGPS
from .resumentrip import ResumenTrip
from .rol import Rol
from .permiso import Permiso
from .rolpermiso import RolPermiso
from .usuariorol import UsuarioRol
from .rutatramo import RutaTramo
from .triptramo import TripTramo
from .tripconductores import TripConductor
from .vehiculoconductor import VehiculoConductor
from .paradasautorizadas import ParadasAutorizadas
from .rutaparada import RutaParada
from .tipodispositivogps import TipoDispositivoGPS
from .triplog import TripLog
from .tipovehiculo import TipoVehiculo